---
language: python
services: docker

env:
  global:
    - IMAGE_NAME: coglinev3/python
  matrix:
    - IMAGE_TAG: ubuntu-16.04
    - IMAGE_TAG: ubuntu-18.04

install:
  # Upgrade Docker and Python
  - pip install molecule docker

before_script:
  # Create roles directory
  - mkdir roles
  # Install required Ansible Role(s)
  - ansible-galaxy install -r requirements.yml -p roles

script:
  # Build Alpine image
  - ansible-playbook python-${IMAGE_TAG}.yml

  # Show os version
  - docker run -it  ${IMAGE_NAME}:${IMAGE_TAG} env TERM=xterm cat /etc/os-release

  # Verify Python 3 is available in the container
  - docker run -it  ${IMAGE_NAME}:${IMAGE_TAG} env TERM=xterm python3 --version
