---
dist: bionic
addons:
  apt:
    packages:
    - docker-ce
    - libssl-dev
    - libffi-dev
    - python3
    - python3-pip
    - python3-setuptools
    - python3-software-properties
    - python3-wheel

language: minimal

services:
  - docker

env:
  global:
    - IMAGE_NAMESPACE: coglinev3
    - IMAGE_NAME: python
  matrix:
    - IMAGE_TAG: alpine-3.11
    - IMAGE_TAG: alpine-3.10
    - IMAGE_TAG: alpine-3.9
    - IMAGE_TAG: centos-7
    - IMAGE_TAG: centos-8
    - IMAGE_TAG: debian-8
      IMAGE_ALTERNATE_TAG: debian-jessie
    - IMAGE_TAG: debian-9
      IMAGE_ALTERNATE_TAG: debian-stretch
    - IMAGE_TAG: debian-10
      IMAGE_ALTERNATE_TAG: debian-buster
    - IMAGE_TAG: ubuntu-19.10
      IMAGE_ALTERNATE_TAG: ubuntu-eoan
    - IMAGE_TAG: ubuntu-18.04
      IMAGE_ALTERNATE_TAG: ubuntu-bionic
    - IMAGE_TAG: ubuntu-16.04
      IMAGE_ALTERNATE_TAG: ubuntu-xenial

install:
  # Install Ansible and Python Docker Module
  - pip3 install ansible docker

before_script:
  # Configure Ansible
  - cp .travis/ansible.cfg ~/.ansible.cfg
  - mkdir -p ~/.ansible && cp .travis/hosts ~/.ansible
  # Show Ansible version
  - ansible --version
  # Create roles directory
  - mkdir -p ~/.ansible/roles
  # Install required Ansible Role(s)
  - ansible-galaxy install -r requirements.yml -p ~/.ansible/roles

script:
  # Build image with Ansible
  - ansible-playbook python-${IMAGE_TAG}.yml

after_success:
  # Start a container from the new created image
  - >
    cid=$(docker run -d --rm --name check_python
    ${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
    tail -f /dev/null)
  # show container os-release
  - docker exec ${cid} env TERM=xterm cat /etc/os-release
  # show container python version
  - >
    docker exec ${cid} env TERM=xterm /bin/bash -c "
    /usr/libexec/platform-python --version
    || python3 --version
    || python --version
    || echo python not available"
  # Stop the container
  - docker stop ${cid}

deploy:
  provider: script
  script: bash scripts/docker_push
  cleanup: false
  on:
    branch: master
