---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    base_image: ubuntu
    base_image_tag: 16.04
    container_name: py_ubuntu_1604
    image_namespace: coglinev3
    image_name: python
    image_tag: ubuntu-16.04
  pre_tasks:
    - name: Make the latest version of the base image available locally.
      docker_image:
        name: '{{ base_image }}:{{ base_image_tag }}'
        source: pull
        force_source: true
    - name: Create the Docker container.
      docker_container:
        image: '{{ base_image }}:{{ base_image_tag }}'
        name: '{{ container_name }}'
        command: sleep infinity
    - name: Add the newly created container to the inventory.
      add_host:
        hostname: '{{ container_name }}'
        ansible_connection: docker
  tasks:
    - name: "Install Python if needed"
      import_role:
        name: "coglinev3.ansible_python"
      delegate_to: '{{ container_name }}'
  post_tasks:
    - name: Commit the container.
      command: >
        docker commit
        --author "Cogline.v3"
        {{ container_name }} {{ image_namespace }}/{{ image_name }}:{{ image_tag }}
    - name: Remove the container.
      docker_container:
        name: '{{ container_name }}'
        state: absent
